### ISSUE TITLE
Anti-pattern: No security context for pods 

### ISSUE THREAD

**Issue by akondasif** [PacktPublishing/Hands-On-Microservices-with-Kubernetes#1]
Dear Colleague,

We are looking to find ways to help developers find security anti-patterns, i.e., violation of security best practices in Kubernetes manifests. We have noticed an instance of `no security context` in one of your Kubernetes manifests. The recommended practice is use of security context for pods. Without defining a security context for the pod, a container may run with root privilege and write permission into the root file system, making the Kubernetes cluster vulnerable. For examples of Kubernetes security anti-patterns we are following our peer-reviewed publication on Kubernetes security best practices (https://arxiv.org/pdf/2006.15275.pdf).

Location of security anti-pattern: https://github.com/PacktPublishing/Hands-On-Microservices-with-Kubernetes/blob/36cba8ff06a18800ce374ea0fc17d54a5211c224/Chapter05/some-other-pod.yaml#L6

**Comment by akondasif** [comment]
Privileged security context is also anti-pattern. 


Location: https://github.com/PacktPublishing/Hands-On-Microservices-with-Kubernetes/blob/36cba8ff06a18800ce374ea0fc17d54a5211c224/Chapter06/privileged-pod.yaml#L11 

Fix: https://github.com/PacktPublishing/Hands-On-Microservices-with-Kubernetes/pull/2

**Comment by saurabhk710** [comment]
Hi @akondasif 
The manifest is a simple pod intended to demonstrate the basics and not full-fledged secure. it is not recommended at all to use pod manifests directly, but use Deployments and StatefulSets.

In addition, the security best practices for Kubernetes have changed since the book was written (e.g pod security policies are deprecated now).
